name: Auto update data
# 这里的空格在readme.md中的badge里需要使用`%20`替换

on: 
  schedule:
    - cron: '0 12 * * 1'
# 按时间更新：https://www.yuque.com/lart/linux/crontab

# https://github.com/graueneko/aktools/blob/master/.github/workflows/autoupdate.yml
# https://github.com/Seniru/LineGraph-TFM/blob/master/.github/workflows/build.yml
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download files
        run: curl -sO https://packagecontrol.io/channel_v3.json
      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "ci: Automated build push" -a | exit 0
      - name: Push changes
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          # `secrets.GITHUB_TOKEN` 是由GITHUB自动生成的
